# Generated by Django 5.1.7 on 2026-02-28 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30, null='True')),
                ('uname', models.CharField(default='user', max_length=30, null='True', unique=True)),
                ('pas', models.CharField(max_length=30)),
                ('rights', models.CharField(default='U', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='watchcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.IntegerField()),
                ('pname', models.CharField(max_length=40)),
                ('rate', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('total', models.IntegerField()),
                ('userid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='watchsales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesno', models.IntegerField(unique=True)),
                ('salesdate', models.DateField(default=datetime.date.today)),
                ('userid', models.IntegerField()),
                ('uname', models.CharField(max_length=30)),
                ('shipment', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=10)),
                ('cardno', models.CharField(max_length=40)),
                ('total', models.IntegerField()),
                ('status', models.CharField(choices=[('New Order', 'New Order'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='New Order', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='watchsalessub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesno', models.IntegerField()),
                ('slno', models.IntegerField()),
                ('pname', models.CharField(max_length=40)),
                ('rate', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='watchstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=30, unique=True, verbose_name='Watch Name')),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField(verbose_name='No of Watchs')),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
