# Generated by Django 4.1.7 on 2026-04-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='watchsales',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchstock',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='watchstock',
            name='category',
            field=models.CharField(blank=True, choices=[('Luxury', 'Luxury'), ('Sport', 'Sport'), ('Casual', 'Casual'), ('Smart', 'Smart'), ('Classic', 'Classic')], default='Classic', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='watchstock',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='watchstock',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='pas',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='uname',
            field=models.CharField(blank=True, default='user', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='watchcart',
            name='pname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='watchsales',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='watchsales',
            name='shipment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watchsales',
            name='status',
            field=models.CharField(choices=[('New Order', 'New Order'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='New Order', max_length=30),
        ),
        migrations.AlterField(
            model_name='watchsales',
            name='uname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='watchsalessub',
            name='pname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='watchstock',
            name='qty',
            field=models.IntegerField(verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='watchstock',
            name='wname',
            field=models.CharField(max_length=100, unique=True, verbose_name='Watch Name'),
        ),
    ]
